### PR TITLE
Fix qemu make

### PR DESCRIPTION
**Pull request by xadaemon**
These tweaks made the qemu make target just work™️ for me

### CODE REVIEW

**Comment by 29jm** [comment]
It's more that ubuntu (or perhaps debian?) dropped support for sdl rather than qemu (it's still in the docs and still works on other distros), but we can't do anything about that so this is a good change either way. Thanks!

**Comment by the-grue** [comment]
I noticed the sdl issue in Ubuntu 20.04.  Seems there are several changes in the newer distros.

**Comment by 29jm** [comment]
@the-grue I don't understand this change though. On archlinux, the latest qemu is still built with sdl2, no patches required. In any case, I only cared about it for its absence-of-ugly-menubar-on-launch, no big deal ^^

**Comment by the-grue** [comment]
@29jm looks like Ubuntu/Debian dropped support for SDL in qemu after 18.04.  This is why I hadn't seen the issue prior to upgrading one machine to 20.04.  Here's an old "Ask Ubuntu" posting about it:

https://askubuntu.com/questions/1146531/qemu-system-i386-sdl-sdl-support-is-disabled-ubuntu-19-04

**Comment by xadaemon** [comment]
I'm using open suse tumbleweed here, sdl support was dropped from qemu here as well

**Pull request merged**
